spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/yoga_db
    username: postgres
    password: postgres
    initialize: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: update

logging:
  level:
    org.hibernate.SQL: debug

---
spring:
  profiles: container
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    initialize: true
