spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/yoga_db
    username: postgres
    password: postgres
    initialize: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: update
  http:
    multipart:
      max-file-size: 2MB
      max-request-size: 15MB

logging:
  level:
    org.hibernate.SQL: debug
    org.jboss.as.ee: debug

---
spring:
  profiles: container
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    initialize: true
